-- Para esse banco de dados o valor da locacao depende da categoria

--Drop the table if it exists, avoid error if script is rerun
DROP TABLE IF EXISTS CLIENTE;
DROP TABLE IF EXISTS CATEGORIA;
DROP TABLE IF EXISTS GENERO;
DROP TABLE IF EXISTS FILME;
DROP TABLE IF EXISTS LOCACAO;

-- Create tables
CREATE TABLE CLIENTE (
    CDCLIENTE INTEGER PRIMARY KEY AUTOINCREMENT,
    NMCLIENTE TEXT NOT NULL,
    TELEFONE TEXT,
    CPF INTEGER NOT NULL UNIQUE 
);

CREATE TABLE CATEGORIA (
    CDCATEGORIA INTEGER PRIMARY KEY AUTOINCREMENT,
    NMCATEGORIA TEXT NOT NULL,
    VLDIARIA REAL DEFAULT 0
);

CREATE TABLE GENERO (
    CDGENERO INTEGER PRIMARY KEY AUTOINCREMENT,
    NMGENERO TEXT NOT NULL UNIQUE
);

CREATE TABLE FILME (
    CDFILME INTEGER PRIMARY KEY AUTOINCREMENT,
    CDCATEGORIA INTEGER,
    CDGENERO INTEGER,
    NMFILME  TEXT NOT NULL UNIQUE,
    DURACAO  INTEGER NOT NULL, --MINUTOS
    SINOPSE  TEXT NOT NULL,
    FOTO  TEXT NOT NULL,
    FOREIGN KEY (CDCATEGORIA) REFERENCES CATEGORIA(CDCATEGORIA) ON DELETE SET NULL,
    FOREIGN KEY (CDGENERO) REFERENCES GENERO(CDGENERO) ON DELETE SET NULL
);

CREATE TABLE LOCACAO (
    CDLOCACAO INTEGER PRIMARY KEY AUTOINCREMENT,
    CDFILME INTEGER NOT NULL,
    CDCLIENTE INTEGER NOT NULL,
    DTLOCACAO TEXT NOT NULL, -- Formato 'YYYY-MM-DD HH:MM:SS'
    DTDEVOLUCAO TEXT, --NULL ATE DEVOLUCAO
    FOREIGN KEY (CDFILME) REFERENCES FILME(CDFILME) ON DELETE CASCADE,
    FOREIGN KEY (CDCLIENTE) REFERENCES CLIENTE(CDCLIENTE) ON DELETE CASCADE
);

-- Índices para otimizar buscas frequentes
CREATE INDEX idx_cliente_cpf ON CLIENTE(CPF);
CREATE INDEX idx_filme_nome ON FILME(NMFILME);
CREATE INDEX idx_locacao_data ON LOCACAO(DTLOCACAO);